server:
  port: 8888

spring:
  application:
    name: MoodHolic
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
  profiles:
    active: private